
name: Frontend CD pipeline(image deploy to ECR and artifacts upload on github)

on:
  push:
    branches:
      - 'ft/*'
      - 'Comflict/Check'
      - 'development'
      - 'update/*'
    pull_request:
      types: [opened, reopened, synchronize, merge, closed]
      branches:
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: dist

      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 730335566159.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: userbanking/frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

